"""add mint field

Revision ID: 7bc4e8b02b9d
Revises: f6ce1348e266
Create Date: 2025-08-09 13:48:40.648729
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7bc4e8b02b9d"
down_revision = "f6ce1348e266"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column("mint_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "mint_url")
    # ### end Alembic commands ###
