"""add mint+currency refund details

Revision ID: 898f00ea481e
Revises: 7bc4e8b02b9d
Create Date: 2025-08-13 16:45:42.148314
"""

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql import sqltypes

# revision identifiers, used by Alembic.
revision = "898f00ea481e"
down_revision = "7bc4e8b02b9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column("refund_mint_url", sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "api_keys",
        sa.Column("refund_currency", sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("api_keys", "mint_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("mint_url", sa.VARCHAR(), nullable=True))
    op.drop_column("api_keys", "refund_currency")
    op.drop_column("api_keys", "refund_mint_url")
    # ### end Alembic commands ###
