"""init

Revision ID: f6ce1348e266
Revises:
Create Date: 2025-08-09 13:28:38.537652
"""

import sqlalchemy as sa
import sqlmodel as sqlm
from alembic import op

# revision identifiers, used by Alembic.
revision = "f6ce1348e266"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("hashed_key", sqlm.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("refund_address", sqlm.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("key_expiry_time", sa.Integer(), nullable=True),
        sa.Column("total_spent", sa.Integer(), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("hashed_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_keys")
    # ### end Alembic commands ###
